person:
        age: 18
        boss: false
        birth: 2017/12/12
        maps: {k1: v1, k2: v2}
        lists:
            - lisi
            - wangwu
            - zhaoliu
        dog:
            name: ${person.last-name}_giggle
            age: 2
        last-name: zhangsan${random.uuid}
spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod